language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - fuse

before_script:
- sudo modprobe fuse

script:
- make test
